name: Build (Galactic)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: humble
      - name: Build rmoss_interfaces
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: humble
